<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>testSuiteDemoOrangeHrm</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>93f5b727-9803-41dd-b24f-3a15a2b41f7b</testSuiteGuid>
   <testCaseLink>
      <guid>18040f3f-6b01-4beb-95c5-86f9f41b7e84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/recordTestDemo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc2d5866-8f36-46e2-932c-863223b14c81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfadf52f-141a-49ba-b9bc-68c242e60919</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>01c819ee-6dbf-4a99-a7a6-84ea8abcad3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/scriptWithVariables</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1aa4e0cd-2857-42a6-9913-7f1ad2a64ee1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67166de0-44e9-4cf5-8ea4-c2ea6b8e0b5e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
